### ISSUE TITLE
`J` and `K` are no longer typeable in the `textarea`/`input`

### ISSUE THREAD

**Issue by brian6932** [RogueArt/google-search-shortcuts#14]
Seems like a recent Google change (rolling out, doesn't seem to work on all browsers for me), changed the `input` class to `textarea`, which broke this extension

**Comment by rajpiskala** [comment]
On a sidenote, were you prompted to update the addon after I pushed fix? I personally didn't receive a prompt to update on my other device, though it seems to be on 0.2.3 already. I'm trying to figure out if it was automatic given it was a patch version or if I should repush it as a minor version to let people know to update it.

**Comment by brian6932** [comment]
> were you prompted to update the addon after I pushed fix?

I didn't have it installed from AMO at the time, I was using my local branch, so Idk. I swapped to the AMO version once I saw it was updated.
Idk how AMO handles auto updates well enough to confidently say tbh. If a patch doesn't auto update, I see nothing wrong with bumping minor ver.
